#cloud-config
package_update: true
package_upgrade: true
packages:
  - git
  - jq
  - vim
  - nano
  - docker
  - docker-compose
users:
  - name: ${USER}
    groups: [wheel]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    ssh-authorized-keys:
      - ${USER_PUB_KEY}
runcmd:
  - sleep 5
  - systemctl enable --now docker
  - chown -R ${USER}:${USER} /home/${USER}
  - curl -fsSL https://code-server.dev/install.sh | su ${USER}
  - su ${USER} -c "sudo systemctl enable --now code-server@${USER}"
write_files:
  - path: /home/${USER}/.config/code-server/config.yaml
    owner: ${USER}:${USER}
    content: |
      bind-addr: 0.0.0.0:1337
      auth: password
      password: ${USER_PASS}
      cert: false
