#cloud-config
package_update: true
package_upgrade: true
packages:
  - git
  - jq
  - vim
  - nano
  - docker
  - docker-compose
runcmd:
  - systemctl enable --now docker
  - chown -R ubuntu:ubuntu /home/ubuntu
  - curl -fsSL https://code-server.dev/install.sh | su ubuntu
  - su ubuntu -c "sudo systemctl enable --now code-server@ubuntu"
write_files:
  - path: /home/ubuntu/.config/code-server/config.yaml
    owner: ubuntu:ubuntu
    content: |
      bind-addr: 0.0.0.0:1337
      auth: password
      password: ${USER_PASS}
      cert: false

# users:
#   - name: dev
#     sudo: ALL=(ALL) NOPASSWD:ALL
#     groups: sudo, docker
#     ssh_authorized_keys:
#       - ${USER_PUB_KEY}
